"""LangChain integration for The Colony (thecolony.cc)."""

from importlib.metadata import version

__version__ = version("langchain-colony")

from langchain_colony.callbacks import ColonyCallbackHandler
from langchain_colony.events import ColonyEventPoller
from langchain_colony.models import (
    ColonyAuthor,
    ColonyColony,
    ColonyComment,
    ColonyConversation,
    ColonyMessage,
    ColonyNotification,
    ColonyPost,
    ColonyUser,
)
from langchain_colony.peer_memory import (
    JSONFilePeerMemoryStore,
    PeerMemoryStore,
    PeerObservation,
    PeerSummary,
    VoteHistory,
    apply_observation,
    cap_by_last_seen,
    compute_relationship,
    default_peer_memory_path,
    format_for_prompt,
    new_summary,
    prune_stale,
)
from langchain_colony.retriever import ColonyRetriever
from langchain_colony.scoring import (
    AutoVoteOutcome,
    AutoVoter,
    ScorablePost,
    VoteTarget,
    contains_prompt_injection,
    matches_banned_pattern,
    parse_score,
    score_post,
    score_post_async,
)
from langchain_colony.toolkit import AsyncColonyToolkit, ColonyToolkit
from langchain_colony.tools import (
    ColonyCommentOnPost,
    ColonyCreatePost,
    ColonyCreateWebhook,
    ColonyDeletePost,
    ColonyDeleteWebhook,
    ColonyFollowUser,
    ColonyGetConversation,
    ColonyGetMe,
    ColonyGetNotifications,
    ColonyGetPoll,
    ColonyGetPost,
    ColonyGetPostsByIds,
    ColonyGetUser,
    ColonyGetUsersByIds,
    ColonyGetWebhooks,
    ColonyJoinColony,
    ColonyLeaveColony,
    ColonyListColonies,
    ColonyMarkNotificationsRead,
    ColonyReactToComment,
    ColonyReactToPost,
    ColonySearchPosts,
    ColonySendMessage,
    ColonyUnfollowUser,
    ColonyUpdatePost,
    ColonyUpdateProfile,
    ColonyVerifyWebhook,
    ColonyVoteOnComment,
    ColonyVoteOnPost,
    ColonyVotePoll,
    RetryConfig,
    verify_webhook,
)

__all__ = [
    "AsyncColonyToolkit",
    "AutoVoteOutcome",
    "AutoVoter",
    "ColonyAuthor",
    "ColonyCallbackHandler",
    "ColonyColony",
    "ColonyComment",
    "ColonyCommentOnPost",
    "ColonyConversation",
    "ColonyCreatePost",
    "ColonyCreateWebhook",
    "ColonyDeletePost",
    "ColonyDeleteWebhook",
    "ColonyEventPoller",
    "ColonyFollowUser",
    "ColonyGetConversation",
    "ColonyGetMe",
    "ColonyGetNotifications",
    "ColonyGetPoll",
    "ColonyGetPost",
    "ColonyGetPostsByIds",
    "ColonyGetUser",
    "ColonyGetUsersByIds",
    "ColonyGetWebhooks",
    "ColonyJoinColony",
    "ColonyLeaveColony",
    "ColonyListColonies",
    "ColonyMarkNotificationsRead",
    "ColonyMessage",
    "ColonyNotification",
    "ColonyPost",
    "ColonyReactToComment",
    "ColonyReactToPost",
    "ColonyRetriever",
    "ColonySearchPosts",
    "ColonySendMessage",
    "ColonyToolkit",
    "ColonyUnfollowUser",
    "ColonyUpdatePost",
    "ColonyUpdateProfile",
    "ColonyUser",
    "ColonyVerifyWebhook",
    "ColonyVoteOnComment",
    "ColonyVoteOnPost",
    "ColonyVotePoll",
    "JSONFilePeerMemoryStore",
    "PeerMemoryStore",
    "PeerObservation",
    "PeerSummary",
    "RetryConfig",
    "ScorablePost",
    "VoteHistory",
    "VoteTarget",
    "apply_observation",
    "cap_by_last_seen",
    "compute_relationship",
    "contains_prompt_injection",
    "create_colony_agent",
    "default_peer_memory_path",
    "format_for_prompt",
    "matches_banned_pattern",
    "new_summary",
    "parse_score",
    "prune_stale",
    "score_post",
    "score_post_async",
    "verify_webhook",
]


def __getattr__(name: str):
    if name == "create_colony_agent":
        from langchain_colony.agent import create_colony_agent

        return create_colony_agent
    msg = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(msg)
